<?php
/**
 * Generated FooConvert block metadata for the AI popup builder.
 *
 * Do not edit this file directly. Run `npm run build:blocks` instead.
 */

defined( 'ABSPATH' ) || exit;

return array(
    'fc/apply-coupon' => array(
        'name' => 'fc/apply-coupon',
        'title' => 'Apply Coupon',
        'description' => 'A WooCommerce coupon apply block.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'uniqueId' => array(
                'type' => 'string',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'code' => array(
                'type' => 'object',
            ),
            'button' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/bar' => array(
        'name' => 'fc/bar',
        'title' => 'Bar',
        'description' => 'A flyout element to display content to visitors.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'postId' => array(
                'type' => 'number',
            ),
            'postType' => array(
                'type' => 'string',
            ),
            'template' => array(
                'type' => 'string',
            ),
            'viewState' => array(
                'type' => 'string',
                'default' => 'open',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'openButton' => array(
                'type' => 'object',
            ),
            'closeButton' => array(
                'type' => 'object',
            ),
            'content' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/bar-close-button' => array(
        'name' => 'fc/bar-close-button',
        'title' => 'Close Button',
        'description' => 'The button used to close the bar.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/bar-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/bar-container' => array(
        'name' => 'fc/bar-container',
        'title' => 'Container',
        'description' => 'Wraps the bar content and close button and positions it within the viewport.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/bar',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/bar-content' => array(
        'name' => 'fc/bar-content',
        'title' => 'Content',
        'description' => 'The primary content container of the bar.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/bar-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/bar-open-button' => array(
        'name' => 'fc/bar-open-button',
        'title' => 'Open Button',
        'description' => 'The button displayed when the bar is closed.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/bar',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/confetti' => array(
        'name' => 'fc/confetti',
        'title' => 'Confetti',
        'description' => 'Plays a confetti effect when the parent popup opens.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/countdown' => array(
        'name' => 'fc/countdown',
        'title' => 'Countdown',
        'description' => 'A countdown block.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'uniqueId' => array(
                'type' => 'string',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'segment' => array(
                'type' => 'object',
            ),
            'digits' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/coupon' => array(
        'name' => 'fc/coupon',
        'title' => 'Coupon',
        'description' => 'A coupon block.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'uniqueId' => array(
                'type' => 'string',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'code' => array(
                'type' => 'object',
            ),
            'button' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/example-block' => array(
        'name' => 'fc/example-block',
        'title' => 'Example Block',
        'description' => 'This block serves no purpose other than to be an example.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'styles' => array(
                'type' => 'object',
            ),
            'content' => array(
                'type' => 'string',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/flyout' => array(
        'name' => 'fc/flyout',
        'title' => 'Flyout',
        'description' => 'A flyout element to display content to visitors.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'postId' => array(
                'type' => 'number',
            ),
            'postType' => array(
                'type' => 'string',
            ),
            'template' => array(
                'type' => 'string',
            ),
            'viewState' => array(
                'type' => 'string',
                'default' => 'open',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'openButton' => array(
                'type' => 'object',
            ),
            'closeButton' => array(
                'type' => 'object',
            ),
            'content' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/flyout-close-button' => array(
        'name' => 'fc/flyout-close-button',
        'title' => 'Close Button',
        'description' => 'The button used to close the flyout.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/flyout-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/flyout-container' => array(
        'name' => 'fc/flyout-container',
        'title' => 'Container',
        'description' => 'Wraps the flyout content and close button and positions it within the viewport.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/flyout',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/flyout-content' => array(
        'name' => 'fc/flyout-content',
        'title' => 'Content',
        'description' => 'The primary content container of the flyout.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/flyout-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/flyout-open-button' => array(
        'name' => 'fc/flyout-open-button',
        'title' => 'Open Button',
        'description' => 'The button displayed when the flyout is closed.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/flyout',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/free-shipping-progress' => array(
        'name' => 'fc/free-shipping-progress',
        'title' => 'Free Shipping Progress',
        'description' => 'A WooCommerce free shipping progress block.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'uniqueId' => array(
                'type' => 'string',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'content' => array(
                'type' => 'object',
            ),
            'bar' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/free-shipping-progress-bar' => array(
        'name' => 'fc/free-shipping-progress-bar',
        'title' => 'Free Shipping Bar',
        'description' => 'Shared free shipping progress bar.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/free-shipping-progress',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'inserter' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/free-shipping-progress-content' => array(
        'name' => 'fc/free-shipping-progress-content',
        'title' => 'Free Shipping Content',
        'description' => 'State content for the free shipping progress block.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/free-shipping-progress',
        ),
        'ancestor' => array(),
        'attributes' => array(
            'state' => array(
                'type' => 'string',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'inserter' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/overlay' => array(
        'name' => 'fc/overlay',
        'title' => 'Overlay',
        'description' => 'An overlay element to display content to visitors.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'postId' => array(
                'type' => 'number',
            ),
            'postType' => array(
                'type' => 'string',
            ),
            'template' => array(
                'type' => 'string',
            ),
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'closeButton' => array(
                'type' => 'object',
            ),
            'content' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/overlay-close-button' => array(
        'name' => 'fc/overlay-close-button',
        'title' => 'Close Button',
        'description' => 'The button used to close the overlay.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/overlay-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/overlay-container' => array(
        'name' => 'fc/overlay-container',
        'title' => 'Container',
        'description' => 'Wraps the overlay content and close button and positions it within the viewport.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/overlay',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
            'inserter' => false,
        ),
    ),
    'fc/overlay-content' => array(
        'name' => 'fc/overlay-content',
        'title' => 'Content',
        'description' => 'The primary content container of the overlay.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/overlay-container',
        ),
        'ancestor' => array(),
        'attributes' => array(),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'html' => false,
        ),
    ),
    'fc/sign-up' => array(
        'name' => 'fc/sign-up',
        'title' => 'Sign Up',
        'description' => 'A simple email sign up form.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'styles' => array(
                'type' => 'object',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'inputs' => array(
                'type' => 'object',
            ),
            'button' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => false,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/split-layout' => array(
        'name' => 'fc/split-layout',
        'title' => 'Split Layout',
        'description' => 'A two-panel layout with one fixed panel and one flexible panel.',
        'category' => 'fooconvert',
        'parent' => array(),
        'ancestor' => array(),
        'attributes' => array(
            'uniqueId' => array(
                'type' => 'string',
            ),
            'settings' => array(
                'type' => 'object',
            ),
            'styles' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
    'fc/split-layout-panel' => array(
        'name' => 'fc/split-layout-panel',
        'title' => 'Panel',
        'description' => 'A panel inside a split layout.',
        'category' => 'fooconvert',
        'parent' => array(
            'fc/split-layout',
        ),
        'ancestor' => array(),
        'attributes' => array(
            'settings' => array(
                'type' => 'object',
            ),
            'styles' => array(
                'type' => 'object',
            ),
        ),
        'supports' => array(
            'lock' => false,
            'multiple' => true,
            'reusable' => false,
            'className' => false,
            'customClassName' => false,
            'html' => false,
        ),
    ),
);
